# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crickcli < Formula
  desc ""
  homepage "https://github.com/prajjwalyd/crickCLI"
  version "0.10"

  on_macos do
    url "https://github.com/prajjwalyd/crickCLI/releases/download/v0.10/crickCLI_0.10_darwin_all.tar.gz"
    sha256 "9cb300d6a4b27241ac00aa36d8989fc6c618c9e6c5aaa4c27699de521c1a01eb"

    def install
      bin.install "crickCLI"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prajjwalyd/crickCLI/releases/download/v0.10/crickCLI_0.10_linux_arm64.tar.gz"
      sha256 "887f31a879da3e2242c5b6d9a1274d06576a800ab867499c8cca2975ffbfd80a"

      def install
        bin.install "crickCLI"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/prajjwalyd/crickCLI/releases/download/v0.10/crickCLI_0.10_linux_amd64.tar.gz"
      sha256 "f210e7cf830c4b685c1b0882167ce95f9eae1355fb2fd81b26e98479bc88e367"

      def install
        bin.install "crickCLI"
      end
    end
  end
end
